name: Build Application

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}  # for getting the cache

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }} # script-file key name. Will be an output of the job to use it in another job
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Publish JS filename
        id: publish  # used in steps.publish.outputs.script-file
        run: find dist -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'  # '::set-output name=script-file::{}' - old syntax. script-file=anyValue

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist

      - name: Deploy application
        run: |
          echo "Building application"
          echo "Build successfully!"
